use std::{fs, path::Path};

fn main() {
    let tailwind_css_path = Path::new("assets/tailwind.css");
    if !tailwind_css_path.exists() {
        fs::create_dir_all("assets")
            .unwrap_or_else(|err| panic!("failed to create `assets/` dir. Error: {}", err));
        fs::write(
            tailwind_css_path,
            "/* placeholder for the `tailwind.css` generated by `dx serve` */",
        )
        .unwrap_or_else(|err| panic!("failed to create dummy `tailwind.css` file at path `{tailwind_css_path:?}`. Error: {}", err));
    }
}
