[package]
name = "rustorio-website"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = { version = "0.7.3", features = ["router", "fullstack"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"], optional = true }
anyhow = { version = "1.0.101", optional = true }
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "runtime-tokio",
], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["sync"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "clap", "anyhow", "dep:sqlx"]
